require("config.monokai-pro")
require("config.lualine")
require("config.alpha")
require("config.mini")
require("config.nvim-treesitter-textobjects")
require("config.oil")
require("config.oil-git-status")
